version: '3.8'

services:
  mongo-test:
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: entertainment_database
    volumes:
      - ./mongo-init-test.js:/docker-entrypoint-initdb.d/mongo-init.js
    container_name: entertainment-app-mongo-test
  server:
    image: ent-test-server
    build:
      context: .
      dockerfile: ./docker/test.server.Dockerfile
    ports:
      - 4000:4000
    depends_on:
      - mongo-test
    environment:
      MONGO_URL: mongodb://the_username:the_password@mongo-test:27017/entertainment_database
      JWT_SECRET: k2ba1bCrKgA9D7bosZzzMhIL02jejmfM
    container_name: entertainment-test-server
