version: '3.8'

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: entertainment_database
    volumes:
      - ./mongo-init-test.js:/docker-entrypoint-initdb.d/mongo-init.js
    container_name: entertainment-app-db
  server:
    image: ent-server
    build:
      context: .
      dockerfile: ./docker/prod.server.Dockerfile
    depends_on:
      - mongo
    environment:
      MONGO_URL: mongodb://the_username:the_password@mongo:27017/entertainment_database
      JWT_SECRET: k2ba1bCrKgA9D7bosZzzMhIL02jejmfM
    ports:
      - 4000:4000
    container_name: entertainment-server
  client:
    image: ent-client
    environment:
      VITE_GRAPHQL: http://localhost:4000/api
      VITE_HOST: http://localhost:4000/
    build:
      context: .
      dockerfile: ./docker/prod.client.Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - server
    container_name: entertainment-client
