name: Production Preview

on:
  push:
    branches:
      - production

jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: npm install root
        run: npm install
      - name: npm install client
        run: cd client && npm install
      - name: npm install server
        run: cd server && npm install
      - name: lint backend
        run: npm run lint:backend
      - name: lint client
        run: npm run lint:client
      - name: Docker test container
        run: docker-compose -f docker-compose.test.yml up -d --build
      - name: List Docker containers
        run: docker ps
      - name: Wait for server to start
        run: sleep 10
      - name: start backend test
        run: npm run test:backend
      - name: start client test
        uses: cypress-io/github-action@v4.2.0
        with:
          working-directory: client
          browser: chrome
          start: npm run dev
